import type { Availability } from '@payload-types'

type CreateAvailability = Omit<
  Availability,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const inactiveRecords: CreateAvailability[] = [
  // Inactive Properties (Parent)
  {
    title: 'Inactive',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:17.675Z',
    slug: 'inactive',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b7b99a1e4304421b440b',
        doc: 101,
        url: '/inactive',
        label: 'Inactive',
      },
    ],
    _status: 'published',
  },
  // Reserved (Child of Inactive Properties)
  {
    title: 'Reserved',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:54.156Z',
    slug: 'reserved',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b7de9a1e4304421b441c',
        doc: 101,
        url: '/inactive',
        label: 'Inactive',
      },
      {
        id: '67b0b7de9a1e4304421b441d',
        doc: 102,
        url: '/inactive/reserved',
        label: 'Reserved',
      },
    ],
    _status: 'published',
  },
  // Occupied (Child of Inactive Properties)
  {
    title: 'Occupied',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'occupied',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b442e',
        doc: 101,
        url: '/inactive',
        label: 'Inactive',
      },
      {
        id: '67b0b8449a1e4304421b442f',
        doc: 103,
        url: '/inactive/occupied',
        label: 'Occupied',
      },
    ],
    _status: 'published',
  },
  // Rented (Child of Inactive Properties)
  {
    title: 'Rented',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:52:50.276Z',
    slug: 'rented',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4441',
        doc: 101,
        url: '/inactive',
        label: 'Inactive',
      },
      {
        id: '67b0b8449a1e4304421b4442',
        doc: 104,
        url: '/inactive/rented',
        label: 'Rented',
      },
    ],
    _status: 'published',
  },
  // Sold (Child of Inactive Properties)
  {
    title: 'Sold',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:50.276Z',
    slug: 'sold',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4451',
        doc: 101,
        url: '/inactive',
        label: 'Inactive',
      },
      {
        id: '67b0b8449a1e4304421b4452',
        doc: 105,
        url: '/inactive/sold',
        label: 'Sold',
      },
    ],
    _status: 'published',
  },
  // On Hold (Child of Inactive Properties)
  {
    title: 'On Hold',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:54:50.276Z',
    slug: 'on-hold',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4461',
        doc: 101,
        url: '/inactive',
        label: 'Inactive',
      },
      {
        id: '67b0b8449a1e4304421b4462',
        doc: 106,
        url: '/inactive/on-hold',
        label: 'On Hold',
      },
    ],
    _status: 'published',
  },
  // No Longer Available (Child of Inactive Properties)
  {
    title: 'No Longer Available',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:55:50.276Z',
    slug: 'no-longer-available',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4471',
        doc: 101,
        url: '/inactive',
        label: 'Inactive',
      },
      {
        id: '67b0b8449a1e4304421b4472',
        doc: 107,
        url: '/inactive/no-longer-available',
        label: 'No Longer Available',
      },
    ],
    _status: 'published',
  },
  // Demolished (Child of Inactive Properties)
  {
    title: 'Demolished',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:56:50.276Z',
    slug: 'demolished',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4481',
        doc: 101,
        url: '/inactive',
        label: 'Inactive',
      },
      {
        id: '67b0b8449a1e4304421b4482',
        doc: 108,
        url: '/inactive/demolished',
        label: 'Demolished',
      },
    ],
    _status: 'published',
  },
]
