import type { Availability } from '@payload-types'

type CreateAvailability = Omit<
  Availability,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const otherRecords: CreateAvailability[] = [
  // Coming Soon
  {
    title: 'Coming Soon',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'coming-soon',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b53a8',
        doc: 202,
        url: '/coming-soon',
        label: 'Coming Soon',
      },
    ],
    _status: 'published',
  },
  // Under Construction
  {
    title: 'Under Construction',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:52:50.276Z',
    slug: 'under-construction',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b53b1',
        doc: 203,
        url: '/under-construction',
        label: 'Under Construction',
      },
    ],
    _status: 'published',
  },
  // Launch Preparation
  {
    title: 'Launch Preparation',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:54:50.276Z',
    slug: 'launch-preparation',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b53d1',
        doc: 204,
        url: '/launch-preparation',
        label: 'Launch Preparation',
      },
    ],
    _status: 'published',
  },
  // Off-Market
  {
    title: 'Off-Market',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:55:50.276Z',
    slug: 'off-market',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b53e1',
        doc: 205,
        url: '/off-market',
        label: 'Off-Market',
      },
    ],
    _status: 'published',
  },
  // Private Listing
  {
    title: 'Private Listing',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:56:50.276Z',
    slug: 'private-listing',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b53f1',
        doc: 206,
        url: '/private-listing',
        label: 'Private Listing',
      },
    ],
    _status: 'published',
  },
  // Archive
  {
    title: 'Archive',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:59:50.276Z',
    slug: 'archive',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b5421',
        doc: 207,
        url: '/archive',
        label: 'Archive',
      },
    ],
    _status: 'published',
  },
  // Historical
  {
    title: 'Historical',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:00:50.276Z',
    slug: 'historical',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b5431',
        doc: 208,
        url: '/historical',
        label: 'Historical',
      },
    ],
    _status: 'published',
  },
]
