import {
  BsCurrencyDollar,
  BsCurrencyEuro,
  BsCurrencyPound,
  BsCurrencyRupee,
  BsCurrencyYen,
} from 'react-icons/bs'
import {
  TbCurrencyBaht,
  TbCurrencyDinar,
  TbCurrencyDirham,
  TbCurrencyFrank,
  TbCurrencyIranianRial,
  TbCurrencyKroneDanish,
  TbCurrencyKroneSwedish,
  TbCurrencyLira,
  TbCurrencyPeso,
  TbCurrencyReal,
  TbCurrencyRiyal,
  TbCurrencyRubel,
  TbCurrencyWon,
  TbCurrencyYuan,
  TbCurrencyZloty,
} from 'react-icons/tb'

export const currencySymbols: Record<
  string,
  React.ComponentType<{ size?: number }>
> = {
  USD: BsCurrencyDollar,
  EUR: BsCurrencyEuro,
  AED: TbCurrencyDirham,
  JPY: BsCurrencyYen,
  GBP: BsCurrencyPound,
  CNY: TbCurrencyYuan,
  AUD: BsCurrencyDollar,
  CAD: BsCurrencyDollar,
  CHF: TbCurrencyFrank,
  HKD: BsCurrencyDollar,
  SGD: BsCurrencyDollar,
  MXN: TbCurrencyPeso,
  KRW: TbCurrencyWon,
  INR: BsCurrencyRupee,
  RUB: TbCurrencyRubel,
  BRL: TbCurrencyReal,
  ZAR: TbCurrencyReal,
  NZD: BsCurrencyDollar,
  TRY: TbCurrencyLira,
  SEK: TbCurrencyKroneSwedish,
  NOK: TbCurrencyKroneSwedish,
  DKK: TbCurrencyKroneDanish,
  PLN: TbCurrencyZloty,
  SAR: TbCurrencyRiyal,
  THB: TbCurrencyBaht,
  IRR: TbCurrencyIranianRial,
  DZD: TbCurrencyDinar,
}
