import type { Property } from '@payload-types'

type FinanceInterface = Property['finance']
type CreateFinance = Record<string, FinanceInterface>

export const financeData: CreateFinance = {
  // 1. barshaApartment
  barshaApartment: {
    market: 'mid-market',
    requiresDeposit: true,
    depositType: 'percentage',
    depositAmount: null,
    depositPercentage: 20,
    hasInstallments: true,
    installmentsNumber: 48,
    installmentAmount: 7083,
    targetResidents: 'professionals',
    investmentPotential: 'high',
    investmentType: 'rental-income',
  },
  // 2. jvcResidence
  jvcResidence: {
    market: 'mid-market',
    requiresDeposit: true,
    depositType: 'percentage',
    depositAmount: null,
    depositPercentage: 25,
    hasInstallments: true,
    installmentsNumber: 60,
    installmentAmount: 6933,
    targetResidents: 'families',
    investmentPotential: 'medium',
    investmentType: 'mixed-use',
  },
  // 3. siliconOasisStudio
  siliconOasisStudio: {
    market: 'economy',
    requiresDeposit: true,
    depositType: 'amount',
    depositAmount: 25000,
    depositPercentage: null,
    hasInstallments: true,
    installmentsNumber: 36,
    installmentAmount: 3889,
    targetResidents: 'singles',
    investmentPotential: 'medium',
    investmentType: 'rental-income',
  },
  // 4. alQuozLoft
  alQuozLoft: {
    market: 'luxury',
    requiresDeposit: true,
    depositType: 'percentage',
    depositAmount: null,
    depositPercentage: 30,
    hasInstallments: true,
    installmentsNumber: 48,
    installmentAmount: 7000,
    targetResidents: 'professionals',
    investmentPotential: 'high',
    investmentType: 'value-appreciation',
  },
  // 5. businessBayFlat
  businessBayFlat: {
    market: 'luxury',
    requiresDeposit: true,
    depositType: 'percentage',
    depositAmount: null,
    depositPercentage: 25,
    hasInstallments: true,
    installmentsNumber: 48,
    installmentAmount: 7719,
    targetResidents: 'executives',
    investmentPotential: 'high',
    investmentType: 'mixed-use',
  },
  // 6. alNahdaHome
  alNahdaHome: {
    market: 'mid-market',
    requiresDeposit: true,
    depositType: 'amount',
    depositAmount: 50000,
    depositPercentage: null,
    hasInstallments: true,
    installmentsNumber: 48,
    installmentAmount: 6875,
    targetResidents: 'families',
    investmentPotential: 'medium',
    investmentType: 'rental-income',
  },
  // 7. mirdifVilla
  mirdifVilla: {
    market: 'luxury',
    requiresDeposit: true,
    depositType: 'percentage',
    depositAmount: null,
    depositPercentage: 30,
    hasInstallments: true,
    installmentsNumber: 72,
    installmentAmount: 9074,
    targetResidents: 'families',
    investmentPotential: 'high',
    investmentType: 'value-appreciation',
  },
  // 8. internationalCityFlat
  internationalCityFlat: {
    market: 'economy',
    requiresDeposit: true,
    depositType: 'amount',
    depositAmount: 30000,
    depositPercentage: null,
    hasInstallments: true,
    installmentsNumber: 36,
    installmentAmount: 4583,
    targetResidents: 'singles',
    investmentPotential: 'medium',
    investmentType: 'rental-income',
  },
  // 9. sportsCityApartment
  sportsCityApartment: {
    market: 'mid-market',
    requiresDeposit: true,
    depositType: 'percentage',
    depositAmount: null,
    depositPercentage: 20,
    hasInstallments: true,
    installmentsNumber: 48,
    installmentAmount: 6417,
    targetResidents: 'professionals',
    investmentPotential: 'medium',
    investmentType: 'mixed-use',
  },
  // 10. alQusaisResidence
  alQusaisResidence: {
    market: 'mid-market',
    requiresDeposit: true,
    depositType: 'amount',
    depositAmount: 45000,
    depositPercentage: null,
    hasInstallments: true,
    installmentsNumber: 48,
    installmentAmount: 5729,
    targetResidents: 'families',
    investmentPotential: 'medium',
    investmentType: 'rental-income',
  },
  // 11. discoveryGardens
  discoveryGardens: {
    market: 'economy',
    requiresDeposit: true,
    depositType: 'amount',
    depositAmount: 35000,
    depositPercentage: null,
    hasInstallments: true,
    installmentsNumber: 48,
    installmentAmount: 5000,
    targetResidents: 'couples',
    investmentPotential: 'medium',
    investmentType: 'rental-income',
  },
  // 12. remramApartment
  remramApartment: {
    market: 'mid-market',
    requiresDeposit: true,
    depositType: 'percentage',
    depositAmount: null,
    depositPercentage: 20,
    hasInstallments: true,
    installmentsNumber: 48,
    installmentAmount: 5667,
    targetResidents: 'families',
    investmentPotential: 'medium',
    investmentType: 'mixed-use',
  },
  // 13. dubailandTownhouse
  dubailandTownhouse: {
    market: 'luxury',
    requiresDeposit: true,
    depositType: 'percentage',
    depositAmount: null,
    depositPercentage: 25,
    hasInstallments: true,
    installmentsNumber: 60,
    installmentAmount: 9000,
    targetResidents: 'families',
    investmentPotential: 'high',
    investmentType: 'value-appreciation',
  },
  // 14. warqaaResidence
  warqaaResidence: {
    market: 'mid-market',
    requiresDeposit: true,
    depositType: 'percentage',
    depositAmount: null,
    depositPercentage: 20,
    hasInstallments: true,
    installmentsNumber: 48,
    installmentAmount: 7000,
    targetResidents: 'families',
    investmentPotential: 'medium',
    investmentType: 'rental-income',
  },
  // 15. karamaFlat
  karamaFlat: {
    market: 'economy',
    requiresDeposit: true,
    depositType: 'amount',
    depositAmount: 30000,
    depositPercentage: null,
    hasInstallments: true,
    installmentsNumber: 36,
    installmentAmount: 5972,
    targetResidents: 'professionals',
    investmentPotential: 'medium',
    investmentType: 'rental-income',
  },
  // 16. tecomApartment
  tecomApartment: {
    market: 'luxury',
    requiresDeposit: true,
    depositType: 'percentage',
    depositAmount: null,
    depositPercentage: 25,
    hasInstallments: true,
    installmentsNumber: 48,
    installmentAmount: 7188,
    targetResidents: 'executives',
    investmentPotential: 'high',
    investmentType: 'mixed-use',
  },
  // 17. deiraCondo
  deiraCondo: {
    market: 'mid-market',
    requiresDeposit: true,
    depositType: 'amount',
    depositAmount: 40000,
    depositPercentage: null,
    hasInstallments: true,
    installmentsNumber: 48,
    installmentAmount: 5313,
    targetResidents: 'professionals',
    investmentPotential: 'medium',
    investmentType: 'rental-income',
  },
  // 18. satwaResidence
  satwaResidence: {
    market: 'economy',
    requiresDeposit: true,
    depositType: 'amount',
    depositAmount: 25000,
    depositPercentage: null,
    hasInstallments: true,
    installmentsNumber: 36,
    installmentAmount: 4444,
    targetResidents: 'singles',
    investmentPotential: 'low',
    investmentType: 'rental-income',
  },
  // 19. rashidiyaHome
  rashidiyaHome: {
    market: 'mid-market',
    requiresDeposit: true,
    depositType: 'percentage',
    depositAmount: null,
    depositPercentage: 20,
    hasInstallments: true,
    installmentsNumber: 48,
    installmentAmount: 6083,
    targetResidents: 'families',
    investmentPotential: 'medium',
    investmentType: 'rental-income',
  },
  // 20. garhoudApartment
  garhoudApartment: {
    market: 'mid-market',
    requiresDeposit: true,
    depositType: 'percentage',
    depositAmount: null,
    depositPercentage: 20,
    hasInstallments: true,
    installmentsNumber: 48,
    installmentAmount: 6833,
    targetResidents: 'professionals',
    investmentPotential: 'high',
    investmentType: 'mixed-use',
  },
}
